version: "2"
services:
  mongo:
    image: mongo
    volumes:
      - ~/mongo-data:/data/db
    expose:
      - 27017
  backend:
    build: .
    ports:
      - "4477:4477"
    links: 
      - mongo
    volumes:
      - ~/ProjectSandbox/Pack97NodeJSBE:/Pack97NodeJSBE
    depends_on:
    - mongo
  frontend:
    image: pack97fe:v0.1
    ports:
      - "80:3003"
    links:
      - backend