version: "2"
services:
  mongo:
    image: mongo
    volumes:
      - ~/mongo-data:/data/db
    ports:
      - "27017:27017"
  backend:
    build: .
    ports:
      - "4477:4477"
    links: 
      - mongo
  frontend:
    image: pack97fe:v0.1
    ports:
      - "80:3003"
    links:
      - backend